# Generated by Django 4.2.3 on 2023-08-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0002_alter_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_joined',
        ),
    ]
