# Generated by Django 4.2.3 on 2023-08-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=50, upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
