# Generated by Django 4.2.3 on 2023-08-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoop', '0005_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
