# Generated by Django 4.2.3 on 2023-08-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoop', '0012_mcategory_user_alter_product_index_together_mproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mproduct',
            name='category',
        ),
        migrations.DeleteModel(
            name='MCategory',
        ),
        migrations.DeleteModel(
            name='MProduct',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
